# Generated by Django 5.2.4 on 2025-08-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTPRApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization / Cooperative')], max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
