# Generated by Django 5.2.4 on 2025-08-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptprapplication',
            name='area_hectares',
        ),
        migrations.RemoveField(
            model_name='ptprapplication',
            name='species',
        ),
    ]
