# Generated by Django 5.2.4 on 2025-08-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0004_cloapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainsawRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=20)),
                ('provision_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeCuttingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('plantation', models.CharField(max_length=500)),
                ('species', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
