# Generated by Django 5.2.4 on 2025-08-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0005_chainsawregistration_treecuttingapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLAGApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LumberDealerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('plantation', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LumberOriginPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('lot_location', models.CharField(max_length=500)),
                ('tree_type', models.CharField(max_length=255)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Volume in cubic meters', max_digits=6)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedlingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLUPApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('project', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeCuttingPublicApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('plantation', models.CharField(max_length=500)),
                ('species', models.CharField(max_length=255)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Volume in cubic meters', max_digits=6)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WPPPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Capacity in m³/year')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
