# Generated by Django 5.2.4 on 2025-08-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0006_flagapplication_lumberdealerapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptprapplication',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ptprapplication',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='ptprapplication',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='ptprapplication',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='ptprapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='ptprapplication',
            name='brgy_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ptpr/brgy_certificates/', verbose_name='Brgy. Certificate'),
        ),
        migrations.AddField(
            model_name='ptprapplication',
            name='land_title_or_tax_declaration',
            field=models.FileField(blank=True, null=True, upload_to='ptpr/land_titles/', verbose_name='Land Title or Tax Declaration'),
        ),
        migrations.AddField(
            model_name='ptprapplication',
            name='letter_request',
            field=models.FileField(blank=True, null=True, upload_to='ptpr/letter_requests/', verbose_name='Letter Request'),
        ),
        migrations.AddField(
            model_name='ptprapplication',
            name='spa_document',
            field=models.FileField(blank=True, null=True, upload_to='ptpr/spa_documents/', verbose_name='SPA Document'),
        ),
        migrations.AddField(
            model_name='ptprapplication',
            name='valid_id_with_signature',
            field=models.FileField(blank=True, null=True, upload_to='ptpr/valid_ids/', verbose_name='Valid ID with Signature'),
        ),
        migrations.AlterField(
            model_name='ptprapplication',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
    ]
