# Generated by Django 5.2.4 on 2025-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0007_remove_ptprapplication_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainsawregistration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='chainsawregistration',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='chainsawregistration',
            name='provision_type',
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/affidavit/', verbose_name='Affidavit of Ownership(Atty.)'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/application_form/', verbose_name='Application Form from DENR'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='chainsaw_specification',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/chainsaw_specification/', verbose_name='Chainsaw Specification from DENR'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='dti',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/dti/', verbose_name='Business Name Registration(DTI)'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='mayors_permit',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/mayors_permit/', verbose_name="Mayor's Permit"),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='permit_sell',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/permit_sell/', verbose_name='Permit to Sell'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='purchase_receipt',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/purchase_receipt/', verbose_name='Purchase of Chainsaw Official Receipt'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='serial_no',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/serial_no/', verbose_name='Stencil of Serial No.'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='spa_document',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/dti/', verbose_name='SPA Document'),
        ),
        migrations.AddField(
            model_name='chainsawregistration',
            name='valid_id_with_signature',
            field=models.FileField(blank=True, null=True, upload_to='chainsaw_registration/dti//', verbose_name='Valid ID with Signature'),
        ),
    ]
