# Generated by Django 5.2.4 on 2025-08-19 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0008_remove_chainsawregistration_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LumberOriginPermit',
            new_name='PrivateLandTimberPermit',
        ),
        migrations.AlterModelOptions(
            name='chainsawregistration',
            options={'verbose_name': 'Chainsaw Registration', 'verbose_name_plural': 'Chainsaw Registration'},
        ),
        migrations.AlterModelOptions(
            name='cloapplication',
            options={'verbose_name': 'Lumber Origin(CLO)', 'verbose_name_plural': 'Lumber Origin(CLO)'},
        ),
        migrations.AlterModelOptions(
            name='covapplication',
            options={'verbose_name': 'COV – Tree Transport', 'verbose_name_plural': 'COV – Tree Transport'},
        ),
        migrations.AlterModelOptions(
            name='flagapplication',
            options={'verbose_name': 'Forest Land Use Agreement', 'verbose_name_plural': 'Forest Land Use Agreement'},
        ),
        migrations.AlterModelOptions(
            name='lumberdealerapplication',
            options={'verbose_name': 'Lumber Dealer', 'verbose_name_plural': 'Lumber Dealer'},
        ),
        migrations.AlterModelOptions(
            name='privatelandtimberpermit',
            options={'verbose_name': 'Private Land Timber', 'verbose_name_plural': 'Private Land Timber'},
        ),
        migrations.AlterModelOptions(
            name='ptprapplication',
            options={'verbose_name': 'Private Tree Plantation', 'verbose_name_plural': 'Private Tree Plantation'},
        ),
        migrations.AlterModelOptions(
            name='seedlingrequest',
            options={'verbose_name': 'Seedling Request', 'verbose_name_plural': 'Seedling Request'},
        ),
        migrations.AlterModelOptions(
            name='slupapplication',
            options={'verbose_name': 'Special Land Use Permit', 'verbose_name_plural': 'Special Land Use Permit'},
        ),
        migrations.AlterModelOptions(
            name='treecuttingapplication',
            options={'verbose_name': 'Tree Cutting (National)', 'verbose_name_plural': 'Tree Cutting (National)'},
        ),
        migrations.AlterModelOptions(
            name='treecuttingpublicapplication',
            options={'verbose_name': 'Tree Cutting (Public)', 'verbose_name_plural': 'Tree Cutting (Public)'},
        ),
        migrations.AlterModelOptions(
            name='wpppermit',
            options={'verbose_name': 'Wood Processing Plant Permit', 'verbose_name_plural': 'Wood Processing Plant Permit'},
        ),
    ]
