# Generated by Django 5.2.4 on 2025-08-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GratuitousPermitMOA',
        ),
    ]
