# Generated by Django 5.2.4 on 2025-08-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0002_delete_gratuitouspermitmoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='GratuitousPermitMOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('regulation_type', models.CharField(choices=[('tree-cutting', 'Tree Cutting or Earth-balling Permit'), ('pollution-control', 'Wastewater or Emission Control'), ('watershed-protection', 'Watershed Protection'), ('pest-management', 'Pest Management Support'), ('climate-buffer', 'Climate Buffer Zoning')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
