# Generated by Django 5.2.4 on 2025-08-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0003_gratuitouspermitmoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=20)),
                ('cultural_type', models.CharField(choices=[('ecotourism', 'Ecotourism Visit / Site Access'), ('environmental-education', 'Environmental Education Request'), ('cultural-heritage', 'Cultural Heritage or Indigenous Knowledge Access'), ('research', 'Academic or Cultural Research'), ('spiritual', 'Spiritual or Traditional Ritual')], max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
