# Generated by Django 5.2.4 on 2025-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0004_wildliferegistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeFarmPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=20)),
                ('habitat_type', models.CharField(choices=[('restoration', 'Habitat Restoration Assistance'), ('native-trees', 'Native Tree Planting Support'), ('wildlife-corridor', 'Wildlife Corridor Maintenance'), ('species-monitoring', 'Habitat Monitoring for Key Species'), ('protected-zone', 'Support for Protected Habitat Zone')], max_length=50)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LocalTransportPermit',
        ),
        migrations.DeleteModel(
            name='MarineResearchClearance',
        ),
    ]
