# Generated by Django 5.2.4 on 2025-08-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0005_wildlifefarmpermit_delete_localtransportpermit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifefarmpermit',
            name='purpose',
        ),
    ]
