# Generated by Django 5.2.4 on 2025-08-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0006_remove_wildlifefarmpermit_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTransportPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=20)),
                ('provision_type', models.CharField(choices=[('seedlings', 'Seedling Distribution'), ('water', 'Water Extraction Access'), ('forest-products', 'Forest Product Collection'), ('wildlife-collection', 'Wildlife/Plant Collection (for research)'), ('bioprospecting', 'Bioprospecting Permit')], max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarineResearchClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=20)),
                ('support_type', models.CharField(choices=[('soil-study', 'Soil Formation Study / Request'), ('biodiversity-monitoring', 'Biodiversity or Ecosystem Monitoring'), ('research', 'Academic Research on Ecological Processes'), ('habitat-mapping', 'Habitat Mapping or Nutrient Survey')], max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLocalTransportPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=20)),
                ('adaptation_type', models.CharField(choices=[('climate-adaptation', 'Climate Adaptation Support'), ('disaster-recovery', 'Ecosystem-based Disaster Recovery'), ('mangrove-restoration', 'Mangrove or Coastal Buffer Zone Restoration'), ('community-resilience', 'Community-Based Resilience Program')], max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
