# Generated by Django 5.2.4 on 2025-08-19 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0007_localtransportpermit_marineresearchclearance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gratuitouspermitmoa',
            options={'verbose_name': 'Gratuitous Permit', 'verbose_name_plural': 'Gratuitous Permit'},
        ),
        migrations.AlterModelOptions(
            name='localtransportpermit',
            options={'verbose_name': 'Local Transport Permit', 'verbose_name_plural': 'Local Transport Permit'},
        ),
        migrations.AlterModelOptions(
            name='marineresearchclearance',
            options={'verbose_name': 'Marine Research Clearance', 'verbose_name_plural': 'Marine Research Clearance'},
        ),
        migrations.AlterModelOptions(
            name='speciallocaltransportpermit',
            options={'verbose_name': 'Special Local Transport Permit', 'verbose_name_plural': 'Special Local Transport Permit'},
        ),
        migrations.AlterModelOptions(
            name='wildlifefarmpermit',
            options={'verbose_name': 'Wildlife Farm Permit', 'verbose_name_plural': 'Wildlife Farm Permit'},
        ),
        migrations.AlterModelOptions(
            name='wildliferegistration',
            options={'verbose_name': 'Wildlife Registration', 'verbose_name_plural': 'Wildlife Registration'},
        ),
    ]
