# Generated by Django 5.2.4 on 2025-08-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandClassificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('number_of_trees', models.PositiveIntegerField()),
                ('reason_for_cutting', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='land_documents/')),
                ('status', models.CharField(choices=[('under_verification', 'Under Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_verification', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
