# Generated by Django 5.2.4 on 2025-08-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAuthorityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('land_location', models.CharField(max_length=255)),
                ('zoning_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('under_verification', 'Under Verification'), ('approved', 'Approved'), ('denied', 'Denied'), ('for_payment', 'For Payment'), ('on_process', 'On Process'), ('released', 'Released')], default='under_verification', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
