# Generated by Django 5.2.4 on 2025-08-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_surveyauthorityapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('construction_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('infrastructure', 'Public Infrastructure'), ('industrial', 'Industrial')], max_length=50)),
                ('environmental_doc', models.FileField(upload_to='construction_docs/')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
