# Generated by Django 5.2.4 on 2025-08-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_agriculturalapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialFreePatentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('proponent_name', models.CharField(max_length=255)),
                ('project_location', models.CharField(max_length=500)),
                ('eia_document', models.FileField(blank=True, null=True, upload_to='residential_free_patent/')),
                ('status', models.CharField(choices=[('under_verification', 'Under Verification'), ('approved', 'Approved'), ('returned', 'Returned'), ('for_inspection', 'For Inspection'), ('under_evaluation', 'Under Evaluation')], default='under_verification', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
