# Generated by Django 5.2.4 on 2025-08-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_residentialfreepatentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPlanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('community', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('tree_volunteer', 'Tree Planting Volunteer'), ('donor', 'Donor'), ('event_organizer', 'Event Organizer')], max_length=50)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('for_compliance', 'For Compliance')], default='pending', max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
    ]
