# Generated by Django 5.2.4 on 2025-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_surveyplanapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyauthorityapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='surveyauthorityapplication',
            name='land_location',
        ),
        migrations.RemoveField(
            model_name='surveyauthorityapplication',
            name='zoning_type',
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='brgy_clearance',
            field=models.TextField(blank=True, null=True, verbose_name='Brgy. Clearance'),
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='confirmation_of_affidavit_of_adjoining_owners',
            field=models.TextField(blank=True, null=True, verbose_name='Confirmation of Affidavit of Adjoining Owners'),
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='dar_certification',
            field=models.TextField(blank=True, null=True, verbose_name='DAR Certification (as to no title issued)'),
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='deed_of_conveyance',
            field=models.TextField(blank=True, null=True, verbose_name='Deed of Conveyance (Deed of Sale/Tax Dec., Etc.)'),
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='denr_ad_certification',
            field=models.TextField(blank=True, null=True, verbose_name='DENR A&D Certification (as to no title issued)'),
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='letter_request',
            field=models.TextField(blank=True, null=True, verbose_name='Letter Request'),
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='sketch_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Sketch Plan'),
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='technical_description',
            field=models.TextField(blank=True, null=True, verbose_name='Technical Description (DENR)'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
