# Generated by Django 5.2.4 on 2025-08-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_remove_surveyauthorityapplication_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyauthorityapplication',
            name='denr_ad_certification',
        ),
        migrations.AddField(
            model_name='surveyauthorityapplication',
            name='denr_and_certification',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/denr_and_certification/', verbose_name='DENR A&D Certification (as to no title issued)'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='brgy_clearance',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/brgy_clearance/', verbose_name='Brgy. Clearance'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='confirmation_of_affidavit_of_adjoining_owners',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/affidavit_confirmation/', verbose_name='Confirmation of Affidavit of Adjoining Owners'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='dar_certification',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/dar_certification/', verbose_name='DAR Certification (as to no title issued)'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='deed_of_conveyance',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/deed_of_conveyance/', verbose_name='Deed of Conveyance (Deed of Sale/Tax Dec., Etc.)'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='letter_request',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/letter_request/', verbose_name='Letter Request'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='sketch_plan',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/sketch_plan/', verbose_name='Sketch Plan'),
        ),
        migrations.AlterField(
            model_name='surveyauthorityapplication',
            name='technical_description',
            field=models.FileField(blank=True, null=True, upload_to='survey_authority/technical_description/', verbose_name='Technical Description (DENR)'),
        ),
    ]
