# Generated by Django 5.2.4 on 2025-08-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_remove_surveyauthorityapplication_denr_ad_certification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agriculturalapplication',
            options={'verbose_name': 'Agricultural Free Patent', 'verbose_name_plural': 'Agricultural Free Patent'},
        ),
        migrations.AlterModelOptions(
            name='landclassificationapplication',
            options={'verbose_name': 'Land Classification Status', 'verbose_name_plural': 'Land Classification Status'},
        ),
        migrations.AlterModelOptions(
            name='residentialfreepatentapplication',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Residential Free Patent', 'verbose_name_plural': 'Residential Free Patent'},
        ),
        migrations.AlterModelOptions(
            name='surveyauthorityapplication',
            options={'verbose_name': 'Survey Authority', 'verbose_name_plural': 'Survey Authority'},
        ),
        migrations.AlterModelOptions(
            name='surveyplanapplication',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Survey Plan', 'verbose_name_plural': 'Survey Plan'},
        ),
    ]
