# Generated by Django 5.2.4 on 2025-08-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('biodiversity', 'Biodiversity'), ('land', 'Land'), ('map', 'Map'), ('forestry', 'Forestry')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='BiodiversityFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Biodiversity Feedback',
                'verbose_name_plural': 'Biodiversity Feedbacks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kiosk.feedback',),
        ),
        migrations.CreateModel(
            name='ForestryFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Forestry Feedback',
                'verbose_name_plural': 'Forestry Feedbacks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kiosk.feedback',),
        ),
        migrations.CreateModel(
            name='LandFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Land Feedback',
                'verbose_name_plural': 'Land Feedbacks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kiosk.feedback',),
        ),
        migrations.CreateModel(
            name='MapFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Map Feedback',
                'verbose_name_plural': 'Map Feedbacks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kiosk.feedback',),
        ),
    ]
