# Generated by Django 5.2.4 on 2025-08-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodiversityfeedback',
            options={'verbose_name': 'Biodiversity Feedback', 'verbose_name_plural': 'Biodiversity Feedback'},
        ),
        migrations.AlterModelOptions(
            name='forestryfeedback',
            options={'verbose_name': 'Forestry Feedback', 'verbose_name_plural': 'Forestry Feedback'},
        ),
        migrations.AlterModelOptions(
            name='landfeedback',
            options={'verbose_name': 'Land Feedback', 'verbose_name_plural': 'Land Feedback'},
        ),
        migrations.AlterModelOptions(
            name='mapfeedback',
            options={'verbose_name': 'Map Feedback', 'verbose_name_plural': 'Map Feedback'},
        ),
    ]
